#!/bin/bash
#####################################################################
#	Program :														#
#			Extract the a series of structures and then write the 	#
#			qchem input file										#
#	Input :															#
#			$1 = test.xyz ; store a series of structure				#
#	Output :														#
#			lots of *.inp											#
#                                                                   #
#   History:                                                        #
# 2022/02/02. Grace, copy writeGauInpV and then rewrite this script.#
#####################################################################

function main(){
    # 1. check input argument and extract necessary info.
    # checkInput $1 

    # # 2. generate qchem option into a file
    # qchemOption # output: qchemOption.tmp

    # # 3. generate qchem input files
    # genqchemInp $1 qchemOption.tmp # output: *.inp, namelist.tmp 
    # rm -f qchemOption.tmp

    # 4. submit qchem job
    # qcsubJob namelist.tmp
    # rm -f namelist.tmp
    # rm -f one.inp 
    # for n in `cat namelist.tmp`
    # do 
    #     cat $n.inp >> one.inp
    #     echo @@@ >> one.inp
    # done 
    # rm -f namelist.tmp
    genQchemSGE 
}

function checkInput(){
    [ "$1" == "" ] && echo "file $1 is not exist, exit" && exit

    natom=$(head -n 1 $1)
    natom_2=$(($natom+2))
    fileLine=$(wc -l $1 | awk '{print $1}')
    nfile=$(( $fileLine/($natom+2) ))

    read -p 'Please key-in the charge: ' charge
    read -p 'Please key-in the multiplicity: ' multi
}

function genqchemInp(){
    # $1 = geometry file
    # $2 = qchemOption.tmp

    rm -f namelist.tmp
    for (( i=1;i<=$nfile;i++))
    do
        head -n $(( $natom_2*$i )) $1 | tail -n $natom_2 > tmp.tmp
        name=$(sed -n '2,2 p' tmp.tmp)
        
        if [ `echo $name | grep -c \-` = 1 ]
        then
            name=n$name
        fi
        
        name=$(echo $name | sed 's/ //g')
        echo "${name}" >> namelist.tmp
        echo "${name}".inp

cat << EOF > "${name}".inp
\$molecule
    $charge $multi
`tail -n $natom tmp.tmp` 
\$end 

EOF

cat $2 >> "${name}".inp

    done

    rm -f tmp.tmp
}

function qchemOption(){
    nstat=6

cat << EOF > qchemOption.tmp
\$rem
    EXCHANGE            BHHLYP !50% HF +  50% Becke88 exchange 
    BASIS               6-31+G*
    UNRESTRICTED        True
    MAX_SCF_CYCLES      500
    SYM_IGNORE          True
    SCF_Algorithm       DIIS_GDM
    SCF_GUESS           Read

    SPIN_FLIP           True
    SET_Iter            100

    CALC_NAC            True 
    CIS_DER_NUMSTATE    $nstat   
    CIS_TRIPLETS        False
    CIS_N_ROOTS         $nstat   
\$end

\$derivative_coupling
   comment https://manual.q-chem.com/5.0/sec-MECPs.html
   1 2 3 4 5 6 
\$end

EOF

for (( i=1; i<=$nstat ;i++))
do 
cat << EOF >> qchemOption.tmp
@@@

\$molecule 
    read
\$end 

\$rem
    JOBTYPE             Force
    EXCHANGE            BHHLYP !50% HF +  50% Becke88 exchange 
    BASIS               6-31+G*
    UNRESTRICTED        True
    MAX_SCF_CYCLES      500
    SYM_IGNORE          True
    SCF_Algorithm       DIIS
    SCF_GUESS           Read

    SPIN_FLIP           True
    SET_Iter            100

    CIS_STATE_DERIV     $i   
    CIS_N_ROOTS         $nstat   
    CIS_TRIPLETS        False
\$end

EOF
done
}

function genQchemSGE(){
cat << EOF > test.sge
#!/bin/bash

### SGE Environment
#$ -S /bin/sh -w w   	        ### Run job through bash shell
#$ -j y							### Join stdout and stderr
#$ -l hostname=$nodelist		### Resource control"
#$ -cwd							### Use current working directory

echo "Working directory is \$SGE_O_WORKDIR"
cd \$SGE_O_WORKDIR

echo 'Job starts'
echo "    Host: \$HOSTNAME"
echo '    Date:' `date`
echo 'Directory:' `pwd` 

### QChem Setup 
export QC=/work/qchem/trunk/developer/$USER/qchem_531
# export QCEXE=/work/qchem/trunk/developer/$USER/qchem_531/build/qcprog.exe
export QCEXE=/opt/qchem/cvs/exe/qcprog.exe.$tag
export QCAUX=/work/qchem/trunk/developer/qchem_common/qcaux
export QCSCRATCH=/scratch/$USER/qchem 
export QCLOCALSCR=/scratch/$USER/qclocal

echo ''
echo == Q-CHEM Environment ==
echo qchem bindir is \$QC
test ! -d \$QCLOCALSCR && make -p \$QCLOCALSCR
echo qchem local scratch is \$QCLOCALSCR
test ! -d \$QCSCRATCH && make -p \$QCSCRATCH
echo qchem scratch is§ \$QCSCRATCH

export PATH=$PATH:/opt/util

time \$QCEXE test.inp scratch >& test.out 
EOF
}

function qcsubJob(){
    # $1 = namelist.tmp
    for name in `cat namelist.tmp`
    do 
        qcsub $name.inp $name.out 
    done 
}

main $1 
