#!/bin/bash
# $1 = geom.xyz 


function main(){
    # 1. Check environmental variables 
    source /work/qchem/trunk/developer/Grace/qcenv.530.sh
    qchemProg="$QC/exe/qcprog.exe"
    checkInput $1 # output variable: $charge, $multi, $natom, $natom_2, $nfile 

    # 2. Calculate nonadiabatic coupling 
    calcNonAd $1 
    
    # 3. Calculate force in different excited state  
    calcForce $1

}

function calcNonAd(){
    # $1 = geometry file 

    # first point 
    sed -n "1, $natom_2 p" $1 > tmp.tmp 
    name_i=$(sed -n "2, 2 p" tmp.tmp) 
    qchemOptionNonad SAD 
    genqchemInp $name_i tmp.tmp 
    # echo $qchemProg 
    $qchemProg $name_i.inp $name_i\_WF > $name_i.out 

    # following points
    for (( i=2;i<=$nfile;i++))
    do 
        # Generate qchem input file 
        ini=$(( 1 + ($i - 1) * $natom_2 ))
        fin=$(( $i * $natom_2 ))
        sed -n "$ini,$fin p" $1 > tmp.tmp
        name=$(sed -n "2, 2 p" tmp.tmp) 
        qchemOptionNonad Read # output: qchemOption.tmp
        genqchemInp $name tmp.tmp 

        cp -r $name_i\_WF $name\_WF
        $qchemProg $name.inp $name\_WF > $name.out 
        name_i=$name
    done 

    rm -f qchemOption.tmp tmp.tmp 
}

function calcForce(){
    # $1 = geometry file 

    for (( i=1;i<=$nfile;i++))
    do 
        # Generate qchem input file 
        ini=$(( 1 + ($i - 1) * $natom_2 ))
        fin=$(( $i * $natom_2 ))
        sed -n "$ini,$fin p" $1 > tmp.tmp
        name_pre=$(sed -n "2, 2 p" tmp.tmp) 

        # calculate force in different states
        for (( j = 0; j<= 1; j++))
        do 
            name=$name_pre\_force\_$j
            qchemOptionForce $j # output: qchemOption.tmp
            genqchemInp $name tmp.tmp 
            $qchemProg $name.inp $name_pre\_WF > $name.out
        done 
    done 

    rm -f qchemOption.tmp tmp.tmp 
}

function checkInput(){
    [ "$1" == "" ] && echo "file $1 is not exist, exit" && exit

    natom=$(head -n 1 $1)
    natom_2=$(($natom+2))
    fileLine=$(wc -l $1 | awk '{print $1}')
    nfile=$(( $fileLine/($natom+2) ))

    read -p 'Please key-in the charge: ' charge
    read -p 'Please key-in the multiplicity: ' multi
}

function genqchemInp(){
    # $1 = name of the file
    # $2 = one geometry file 

cat << EOF > $1.inp
\$molecule
    $charge $multi
`tail -n $natom $2` 
\$end

EOF
cat qchemOption.tmp >> $1.inp
}

function qchemOptionNonad(){
    # $1 = Read or SAD
cat << EOF > qchemOption.tmp
\$rem
    EXCHANGE            BHHLYP !50% HF +  50% Becke88 exchange 
    BASIS               6-31+G*
    UNRESTRICTED        True
    MAX_SCF_CYCLES      500
    SYM_IGNORE          True
    SCF_Algorithm       DIIS
    SCF_GUESS           $1 

    SPIN_FLIP           True
    SET_Iter            100

    CALC_NAC            True 
    CIS_DER_NUMSTATE    2   
    CIS_TRIPLETS        False
    CIS_N_ROOTS         2
\$end

\$derivative_coupling
   comment https://manual.q-chem.com/5.0/sec-MECPs.html
    1 2    
\$end

EOF
}

function qchemOptionForce(){
    # $1 = idx. of state 
cat << EOF > qchemOption.tmp
\$rem
    JOBTYPE             Force
    EXCHANGE            BHHLYP !50% HF +  50% Becke88 exchange 
    BASIS               6-31+G*
    UNRESTRICTED        True
    MAX_SCF_CYCLES      500
    SYM_IGNORE          True
    SCF_Algorithm       DIIS
    SCF_GUESS           Read

    SPIN_FLIP           True
    SET_Iter            100

    CIS_STATE_DERIV     $1
    CIS_TRIPLETS        False
\$end

EOF
}

main $1 