#!/bin/bash
# 
# Input: 
#   $1 = time step in a.u. 
# 
# Output:
#   1. workTraj.dat 
#   2. fullTraj.dat 
#   3. fail1pt.dat 
#   4. restTraj.dat
# 
# 2022/08/23, Grace, H.G.Chuang@leeds.ac.uk
# 

tstep=$1
if [ $tstep == '10.' ]
then 
    totpt=900
elif [ $tstep == '2.5' ]
then 
    totpt=3003
fi 
fileRoot='traj_'

function main(){

    printHeader

    calcBody

    printStatic
}

function calcBody(){

    workTraj=0
    fullTraj=0
    fail1pt=0

    ls | grep $fileRoot | sort -n -t _ -k 2 > fileList.tmp 

    rm -f workTraj.dat fullTraj.dat fail1pt.dat restTraj.dat body.tmp 
    for filename in `cat fileList.tmp`
    do
        nfile=$(ls $filename | wc -l)
        if [ $nfile -gt 1 ] # job is running or finished or failed 
        then
            workTraj=$(( $workTraj + 1)) 
            lastpt=$(ls $filename | grep nonad.out | wc -l ) 
            lastpt=$(( $lastpt -1 ))
            
            echo $filename | sed "s/$fileRoot//g" >> workTraj.dat 

            if [ -z $lastpt  ] 
            then 
                lastpt=1
            fi 
            finalTime=$(awk "BEGIN {print $lastpt * $tstep * 2.4189 * 10^-2 }")
            
            if [ $lastpt -eq $totpt ] 
            then 
                fullTraj=$(( $fullTraj + 1 )) 
                echo $filename | sed "s/$fileRoot//g" >> fullTraj.dat 
            elif [ $lastpt -eq 1 ] 
            then 
                fail1pt=$(( $fail1pt + 1 )) 
                echo $filename | sed "s/$fileRoot//g" >> fail1pt.dat 
            else 
                echo $filename | sed "s/$fileRoot//g" >> restTraj.dat
            fi 
        
            echo $filename $nfile $lastpt $finalTime 
        fi 
    done 
    rm -f fileList.tmp 
}

function printHeader(){
    echo '--------------------------------'
    echo "time step: $tstep a.u. "
    echo 'file  nfiles lastpoint time(fs)'
    echo '--------------------------------'

}

function printStatic(){
    echo '--------------------------------'
    echo ''
    echo 'Statistic result: workTraj.dat, fullTraj.dat, fail1pt.dat, restTraj.dat'
    echo "total: $workTraj " 
    echo ''
    echo "full: $fullTraj "
    echo "fail@1pt: $fail1pt" 
    echo "rest: $(( $workTraj - $fullTraj - $fail1pt)) "
    echo '--------------------------------'
}

main $@