#!/bin/bash
# 
# Input: 
#   $1 = time step in a.u. 
# 
# Output:
#   1. workTraj.dat 
#   2. fullTraj.dat 
#   3. fail1pt.dat 
#   4. restTraj.dat
# 
# 2022/08/23, Grace, H.G.Chuang@leeds.ac.uk
# 

function main(){

    setParameters $@

    printHeader

    calcBody

    printStatic
}

function setParameters(){

    tstep=$1
    if [ $tstep == '10.' ]
    then 
        totpt=900
    elif [ $tstep == '2.5' ]
    then 
        totpt=3003
    fi 
    fileRoot='traj_'

    # test file (e.g. traj_1) is exist or not to see cloning 
    nbranch=0 # default: nbranch = 0; no cloning 
    if [ -d $fileRoot\1\/1 ] 
    then 
        nbranch=1
    fi 
}

function calcBody(){

    workTraj=0
    fullTraj=0
    fail1pt=0

    ls | grep $fileRoot | sort -n -t _ -k 2 > fileList.tmp
    if [ $nbranch == 1 ]
    then 
        # cloning 
        rm -f file.tmp 
        for n in `cat fileList.tmp `
        do 
            subDir=( $(ls $n) )  
        
            for (( i=0; i<${#subDir[@]}; i++ ))
            do 
                echo $n\/${subDir[@]} >> file.tmp 
            done 

        done 
        mv file.tmp fileList.tmp 
    fi 

    rm -f workTraj.dat fullTraj.dat fail1pt.dat restTraj.dat body.tmp 
    for filename in `cat fileList.tmp`
    do
        nfile=$(ls $filename | wc -l)
        if [ $nfile -gt 1 ] # job is running or finished or failed 
        then
            workTraj=$(( $workTraj + 1 )) 
            lastpt=$(ls $filename | grep -c nonad.out ) 
            lastpt=$(( $lastpt - 1 ))
            
            echo $filename | sed "s/$fileRoot//g" >> workTraj.dat 

            if [ -z $lastpt  ] 
            then 
                lastpt=1
            fi 
            finalTime=$(awk "BEGIN {print $lastpt * $tstep * 2.4189 * 10^-2 }")
            
            if [ $lastpt -eq $totpt ] 
            then 
                fullTraj=$(( $fullTraj + 1 )) 
                echo $filename | sed "s/$fileRoot//g" >> fullTraj.dat 
            elif [ $lastpt -eq 1 ] 
            then 
                fail1pt=$(( $fail1pt + 1 )) 
                echo $filename | sed "s/$fileRoot//g" >> fail1pt.dat 
            else 
                echo $filename | sed "s/$fileRoot//g" >> restTraj.dat
            fi 

            
            if [ $nbranch == 1 ]
            then 
                subname=$( echo $filename | cut -d '/' -f 2 ) 
                if [ $subname ==  1 ]
                then 
                    filename=$( echo $filename | cut -d '/' -f 1 )
                else 
                    filename=$( echo $filename | cut -d '/' -f 2 )
                fi 
            fi 
            printf "%-10s %-6s %-10s %-10s\n" $filename $nfile $lastpt $finalTime

        fi 
    done 
    rm -f fileList.tmp 
}

function printHeader(){
    head1='file' 
    head2='nfiles'
    head3='lastpoint' 
    head4='time(fs)'
    echo '-------------------------------------'
    echo "time step: $tstep a.u. "
    printf '%-10s %-6s %-10s %-10s\n' $head1 $head2 $head3 $head4 
    echo '-------------------------------------'

}

function printStatic(){
    echo '-------------------------------------'
    echo ''
    echo 'Statistic result: workTraj.dat, fullTraj.dat, fail1pt.dat, restTraj.dat'
    echo "total: $workTraj " 
    echo ''
    echo "full: $fullTraj "
    echo "fail@1pt: $fail1pt" 
    echo "rest: $(( $workTraj - $fullTraj - $fail1pt)) "
    echo '-------------------------------------'
}   

main $@