#!/bin/bash
########################################################################
# 
# Input:
#   $1 = Dima sampling file 
#   $2 = Atom list 
# 
# Output: 
#   *.iniPM (a.u.)
# 
# 2022/11/05, Grace, g.h.chuang@leeds.ac.uk
# 
########################################################################

keyword1=Geometry
keyword2=Momenta
namehead=$(echo $1 | cut -d '.' -f 1)
fileExten=iniPM

input=$1 
atomlist=( $(cat $2) )
natom=$( echo ${#atomlist[@]} )
totL=$(grep -c "$keyword1" $input )

rm -f $1*.iniPM 
for (( i = 1 ; i <= $totL ; i++ ))
do 
    name=$namehead\_$i\.$fileExten

    grep -A $natom "$keyword1 $i" $input | tail -n $natom > tmp 

    for ((n=1;n<=$natom;n++))
    do 
        coord=( $(sed -n "$n,$n p" tmp | sed 's/e/E/g' ) )

        idx=$(($n-1))
        echo ${atomlist[$idx]} ${coord[@]} >> $name 
        # printf "%2s \t %.8f \t %.8f \t %.8f \n" $(echo ${atomlist[$idx]} ${coord[@]} ) >> $name
    done 

    echo $keyword2 >> $name 
    grep -A $natom "$keyword2 $i" $input | tail -n $natom | sed 's/e/E/g' > tmp 
    cat tmp >> $name 
done 
rm -f tmp 
