#!/bin/bash
# 
# Input:
#       $1 = list of directory name for analysing 
#       $2 = selected bond index 
# 
# Pre-request: 
#   ana1traj: analyse the result of one single trajectory
# 
# 2022/12/15, Grace, H.G.Chuang@leeds.ac.uk
#  

fileRoot='ana_'
home=`pwd`
covB_up=2.0

function main(){
    echo '-----------------------------------'
    echo "Bond break = larger than $covB_up ang."
    echo '-----------------------------------'
    echo 'traj. #t(fs) #bonds | $(bond name)'
    echo '-----------------------------------'
    for n in `cat $1`
    do  
        cd $home/$fileRoot$n
        bond_info=( $(ana1traj Bonds.dat $home/$2 $covB_up) ) 
        echo $n ${bond_info[@]}
    done 
    echo '-----------------------------------'
}

main $@