#!/bin/bash
# 
# Purpose: 
#   Run many trajectories. 
# 
# Input: 
#   $1 = list of subdirectory name 
#   $2 = time step in a.u. 
#   $3 = 0 or 1, 0 = no cloning, 1 = have cloning
# 
# Pre-requist: 
#   runNAMD_head
# 
#     2022/08/22, Grace, H.G.Chuang@leeds.ac.uk
# 

function main(){
    # 
    # Depends on how expansive of the electronic structure calculation and computational resource we have, we need to choose different strategies to run molecular dynamics. 
    # 

    # Set global variables
    parameters $@

    # 
    # 1. Run jobs on single node
    #
    # oneNode $@
    # 

    # 2. Run jobs on multiple nodes (use `screen` to continue the propagation)
    # 
    manyNodes $@
}

function parameters(){
    dirRoot='traj_'
    fileRoot='g_'
    home=`pwd`
    numfile_threshold='10'
    tstep=$2 
    nbranch=$3

    runNAMD_prog='/home/home02/chmhch/NAMD_src/runNAMD_slave'
}

function oneNode(){
    

    for Fileidx in `cat $1`
    do 
        firstPt=$(test1stPT $Fileidx)
        
        cd $home/$dirRoot$Fileidx

        $runNAMD_prog $firstPt $tstep $nbranch
    done 

}

function manyNodes(){

    for Fileidx in `cat $1`
    do
        firstPt=$(test1stPT $Fileidx)
        echo $firstPt

        # if [ $nbranch == 0 ]
        # then 
        #     screen -d -m bash -c "cd $home/$dirRoot$Fileidx; $runNAMD_prog $firstPt $tstep $nbranch"

        # elif [ $nbranch == 1 ]
        # then 
        #     # FIXME: only for the first run, not continuous 

        #     screen -d -m bash -c "cd $home/$dirRoot$Fileidx/1; $runNAMD_prog $firstPt $tstep $nbranch "

        # fi 
    done 
}

function test1stPT(){
    # 
    #   If the selected directory only has one file (molecular position and momentum file with the file extension as '.iniPM', then it goes to the first mode which calculate the initial electronic wavefunction, or it goes to the second mode which reads the existed electronic wavefunction.)
    # 
    #   For the second mode, it only support the second run for now. 
    # 
    # Input: 
    #   $1 = file index 
    # 
    # Output: 
    #   $firstPt
    # 
    
    fileidx=$1 

    cd $home 
    numfile=$(ls $dirRoot$fileidx | grep -c .out )
        
    # If the number of file is less than $numfile_threshold, start trajectory form the first point. (i.e. calculate directory *_WF for storing wavefunction)
    if [ $numfile -lt $numfile_threshold ]
    then 
        # First mode, calculate electronic wavefunction.
        firstPt="$fileRoot$fileidx.iniPM"
    else 
        # Second mode, read existed electronic wavefunction. Use the second last point to start the new calculation.
        firstPt=$( ls  $home/$dirRoot$fileidx | grep _nonad.out | sort -n -t _ -k 3 | tail -n 2 | head -n 1  )
    fi 

    # return value 
    echo $firstPt
}

main $@ 